//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssesmentApplication.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table1
    {
        public string DuesMembSSN { get; set; }
        public string DuesMembTempPensionNo { get; set; }
        public string DuesMembPermPensionNo { get; set; }
        public string DuesMembStartDate { get; set; }
        public string DuesMembBillStatus { get; set; }
        public string DuesMembEndDate { get; set; }
        public string DuesMembLastName { get; set; }
        public string DuesMembFirstName { get; set; }
        public string DuesMembAddress1 { get; set; }
        public string DuesMembAddress2 { get; set; }
        public string DuesMembCity { get; set; }
        public string DuesMembState { get; set; }
        public string DuesMembZipCode { get; set; }
        public string DuesMembPhone { get; set; }
        public string DuesMembEmailAddress { get; set; }
        public string DuesMembDateEntered { get; set; }
        public string DuesMembBirthDate { get; set; }
        public string DuesMembRetirementDate { get; set; }
        public string DuesMembBenefitDate { get; set; }
        public string DuesMembDeathDate { get; set; }
        public string DuesMembSpouseLastName { get; set; }
        public string DuesMembSpouseFirstName { get; set; }
        public string DuesMembMarriageDate { get; set; }
    }
}
